### ISSUE TITLE
Ye projekt kya tumhade baap ka he? 🤬

### ISSUE THREAD

**Issue by rumbleFTW** [gSayak/image-storyteller#1]
🤬🤬🤬🤬😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠👿👿👿👿👿👿👿👿👿👿👿👿👿👿👿👿👿😤😤😤😤😤😤😤😤😤😤😤😤😤😤

**Comment by gSayak** [comment]
Naii, raju bhai ka hai!! 

Raju bhaaaaaaieeeee
